### ISSUE TITLE
Recruitment Process Residual Estimates and Plot affected by parameter labeling issue

### ISSUE THREAD

**Issue by tbuehrens** [casruff/Skagit-River-Steelhead-Forecast#4]
res_ln_rec is the recruitment process residuals in the Ar1 model, whereas it is the innovations in the AR1MA1 model...may want to re-label so w(t) are innovations in the AR1MA1 model. The effects are minor since almost all the model weight goes to AR1, but if weights were more equal, this would be a big problem because we are model-averaging to sets of params that don't represent the same thing

**Comment by casruff** [comment]
Thanks for pointing this out. I was going to flag that when I was updating the results to accommodate model averaging but evidently forgot.

**Comment by casruff** [comment]
so to clarify, res_ln_rec(t) are the process residuals/innovations in the Ar1 model and w(t) are the innovations in the AR1MA1 model.

**Comment by tbuehrens** [comment]
Hey Casey! Apologies--the original issue here is wrong. I will still supply a fix, but it is only needed for the fully non-centered version. For the the partial and the fully centered, res_ln_rec[t] are the same thing, which is the process errors. I mispoke earlier. What through me off is the parameterization of the original model...we should chat about the source of my confusion later if you have a chance...too much to explain here. Suffice it to say, I'll push the update for the fully non-centered and close this once i've done that.

**Comment by tbuehrens** [comment]
Ok, I just submitted a pull request to your main branch with the two fixes noted above. res_ln_Rec should be consistent across models now. Also changed prior for first recruitment residual so it is defined the same too
